version: '3.8'
services:
  web_server:
    image: nginx:latest
    container_name: kadai_web_server
    ports:
      - 80:80
    depends_on:
      - application
    volumes:
      - ../:/2021kadai
      - ./containers/nginx/logs:/var/log/nginx
      - ./containers/nginx/conf.d:/etc/nginx/conf.d/
    working_dir: "/2021kadai"
    environment:
      - TZ=${TZ}
  application:
    container_name: kadai_application
    build:
      context: .
      args:
        - TZ=${TZ}
      dockerfile: ./containers/php/Dockerfile
    depends_on:
      - db_server
    volumes:
      - ../:/2021kadai
    working_dir: "/2021kadai"
    environment:
      - TZ=${TZ}
  db_server:
    image: postgres:latest
    container_name: kadai_db_server
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgres
    environment:
      - TZ=${TZ}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  postgres-volume:

